[package]
name = "static-fsm"
version = "0.1.0"
edition = "2021"

[dependencies]
fsm_macro = { version = "0.1", path = "../fsm_macro" }

[dev-dependencies]
fsm_macro = { version = "0.1", path = "../fsm_macro" }

